In [1]:
#import all the required libraries
import pandas as pd
import numpy as np
import scipy.stats as stats


Imagine youare data analyst working for a retail company , The company wants to know if customer prefrence for different age groups. To invastigate this you conduct a survey and collect the foloowing data.


In [2]:
observed_data = np.array([[50, 30 , 20],
                         [30,40,30],
                         [20,30,50]])


Perform chi Square test

In [10]:
chi2_test, p_val, dof, expected_data= stats.chi2_contingency(observed_data)

In [11]:
print(chi2_test)

30.0


In [12]:
print(expected_data)

[[33.33333333 33.33333333 33.33333333]
 [33.33333333 33.33333333 33.33333333]
 [33.33333333 33.33333333 33.33333333]]


In [13]:
print(p_val)

4.894437128029217e-06


In [14]:
print(dof)

4


Final conclusion

In [15]:
alpha = 0.05

if p_val < alpha:
  print('Reject the null hypothesis')
else:
  print("Fail to reject the null hypothesis")


Reject the null hypothesis
